### ISSUE TITLE
THREEjs rotation property not tweening

### ISSUE THREAD

**Issue by mattrei** [mattdesl/tweenr#3]
Hi Matt,

I have a strange problem with tweenr. Tweening the `position` or `scale` property of a THREEjs object does work however with the `rotation` property nothing happens.

Tweening the rotation property with the tween.js library does work. What makes the rotation property so special?

Thanks,
Matthias

**Comment by mattdesl** [comment]
Sorry for the long delay. This is because THREE.Euler uses `get x ()` instead of a getter/setter property, so it isn't enumerable.

Now the algorithm looks for enumerable keys of the passed options object `{ x: 0, duration: 1 }`, but just does a simple `key in target` test to see if the target has that key. This should fix this issue.

The patch is upstream in `tween-objects` so you may need to delete your node_modules to update, or:

```sh
npm install tweenr@latest --save
```
